=== SerchErri/lippia-low-code-sample-project/src/test/resources/jsons/schemas/responseAddNewTimeEntry.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "tagIds": {
      "type": "null"
    },
    "userId": {
      "type": "string"
    },
    "billable": {
      "type": "boolean"
    },
    "taskId": {
      "type": "null"
    },
    "projectId": {
      "type": "string"
    },
    "timeInterval": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string"
        },
        "end": {
          "type": "string"
        },
        "duration": {
          "type": "string"
        }
      },
      "required": [
        "start",
        "end",
        "duration"
      ]
    },
    "workspaceId": {
      "type": "string"
    },
    "isLocked": {
      "type": "boolean"
    },
    "customFieldValues": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "customFieldId": {
              "type": "string"
            },
            "timeEntryId": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "customFieldId",
            "timeEntryId",
            "value",
            "name",
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "customFieldId": {
              "type": "string"
            },
            "timeEntryId": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "customFieldId",
            "timeEntryId",
            "value",
            "name",
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "customFieldId": {
              "type": "string"
            },
            "timeEntryId": {
              "type": "string"
            },
            "value": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "customFieldId",
            "timeEntryId",
            "value",
            "name",
            "type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "customFieldId": {
              "type": "string"
            },
            "timeEntryId": {
              "type": "string"
            },
            "value": {
              "type": "null"
            },
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            }
          },
          "required": [
            "customFieldId",
            "timeEntryId",
            "value",
            "name",
            "type"
          ]
        }
      ]
    },
    "type": {
      "type": "string"
    },
    "kioskId": {
      "type": "null"
    }
  },
  "required": [
    "id",
    "description",
    "tagIds",
    "userId",
    "billable",
    "taskId",
    "projectId",
    "timeInterval",
    "workspaceId",
    "isLocked",
    "customFieldValues",
    "type",
    "kioskId"
  ]
}

=== SerchErri/lippia-low-code-sample-project/src/test/resources/jsons/schemas/responseBulkEditTimeEntries.json
{
  "id": "string",
  "description": "string",
  "tagIds": null,
  "userId": "string",
  "billable": true,
  "taskId": null,
  "projectId": "string",
  "timeInterval": {
    "start": "2021-01-01T01:00:00Z",
    "end": "2021-01-01T00:00:00Z",
    "duration": "string"
  },
  "workspaceId": "string",
  "isLocked": false,
  "customFieldValues": [
    {
      "customFieldId": "string",
      "timeEntryId": "string",
      "value": 0,
      "name": "string",
      "type": "string"
    },
    {
      "customFieldId": "string",
      "timeEntryId": "string",
      "value": 0,
      "name": "string",
      "type": "string"
    },
    {
      "customFieldId": "string",
      "timeEntryId": "string",
      "value": null,
      "name": "string",
      "type": "string"
    },
    {
      "customFieldId": "string",
      "timeEntryId": "string",
      "value": "string",
      "name": "string",
      "type": "string"
    }
  ],
  "type": "string",
  "kioskId": null
}
